spring:
  application:
    name: api-gateway
  # Java configuration RouteConfig.class contains all required routes (including shc, sam, sns-mock, saludpay and catalog)
  cloud:
    gateway:
      loadbalancer:
        enabled: true

  # Seguridad: si usas Spring Security en el gateway, desactiva CSRF etc.
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8081  # si validas tokens en gateway

server:
  port: 8080

# Para evitar logs excesivos de Reactor Netty
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO