server:
  port: 8087
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/shc_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
application:
  name: sps-shc-service
rabbitmq:
  queue: shc.queue
