CREATE DATABASE IF NOT EXISTS sps_auth_db
DEFAULT CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS sps_catalog_db
DEFAULT CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS sps_purchase_db
DEFAULT CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS saludpay_db
DEFAULT CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS shc_db
DEFAULT CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS sam_db
DEFAULT CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS sns_db
DEFAULT CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

GRANT ALL PRIVILEGES ON sps_auth_db.* TO 'sps_user'@'%';
GRANT ALL PRIVILEGES ON sps_catalog_db.* TO 'sps_user'@'%';
GRANT ALL PRIVILEGES ON sps_purchase_db.* TO 'sps_user'@'%';
GRANT ALL PRIVILEGES ON saludpay_db.* TO 'sps_user'@'%';
GRANT ALL PRIVILEGES ON shc_db.* TO 'sps_user'@'%';
GRANT ALL PRIVILEGES ON sam_db.* TO 'sps_user'@'%';
GRANT ALL PRIVILEGES ON sns_db.* TO 'sps_user'@'%';

FLUSH PRIVILEGES;

USE sps_auth_db;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

USE sps_catalog_db;

CREATE TABLE IF NOT EXISTS planes (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    descripcion TEXT,
    precio DECIMAL(12,2) NOT NULL,
    convenio VARCHAR(100),
    activo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

USE sps_purchase_db;

CREATE TABLE IF NOT EXISTS compras (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    estado VARCHAR(50) NOT NULL,
    total DECIMAL(12,2) NOT NULL,
    payload JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
);

USE saludpay_db;

CREATE TABLE IF NOT EXISTS pending_payments (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    CompraId BIGINT NOT NULL,
    ClienteId BIGINT NOT NULL,
    Total DECIMAL(12,2) NOT NULL,
    Estado VARCHAR(50) NOT NULL,
    CreatedAt DATETIME(6),
    UpdatedAt DATETIME(6)
);

USE shc_db;

CREATE TABLE IF NOT EXISTS historias_clinicas (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    compra_id BIGINT NOT NULL,
    cliente_id BIGINT NOT NULL,
    descripcion TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

USE sam_db;

CREATE TABLE IF NOT EXISTS agendas (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    compra_id BIGINT NOT NULL,
    servicio VARCHAR(150) NOT NULL,
    doctor VARCHAR(150) NOT NULL,
    fecha_cita DATETIME,
    estado VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);